### ISSUE TITLE
Broker Parameters

### ISSUE THREAD

**Issue by NavleenKaur-24** [codedellemc/ecs-cf-service-broker#62]
From where can I get the Broker parameters , can I push the jar created as a CF App?

**Comment by spiegela** [comment]
@NavleenKaur-24 There are some descriptions of the configuration parameters on the README of the project.  I've also recently added a new [Wiki page](https://github.com/emccode/ecs-cf-service-broker/wiki) to add more details about the configuration, since that's the greatest source of confusion.

As you can see on the page, I have planned future sections, but the configuration piece seemed like the most important by far.

Please let me know if this page clears up your questions.

Thanks!

**Comment by spiegela** [comment]
@NavleenKaur-24, does the wiki page linked above resolve your question about config parameters?  Also, I realize, I neglected to answer your other question:  Yes, you can push the resulting jar as a CF app.

**Comment by Rohitverma47** [comment]
@spiegela With the help of the jar file, we pushed the broker application  but in the end the instance of the application is down and doesn't start

**Comment by spiegela** [comment]
Typically, this is because the broker can't connect to the ECS management API.  Please check the following settings:

1.  Make sure that the [`management-endpoint` parameter](https://github.com/emccode/ecs-cf-service-broker/wiki#broker-configuration) is addressing the ECS management API, which is typically running on port **4443** -- not the S3 endpoint.  Also make sure that the CF environment has access to the port.
2. Make sure that the `namespace`, `replication-group` and `base-url` parameters are configured with names are exist in the ECS configuration, and make sure that the [Base URL configured in ECS](https://www.emc.com/techpubs/ecs/ecs_use_s3_apps_with-1.htm#GUID-E0B2F3AE-03CC-4950-86FD-8A26D97372DA) is valid, and resolves via DNS.
3. Lastly, make sure that the `username` & `password` parameters represent a valid [**management user** account](http://www.emc.com/techpubs/ecs/users_authprov_and_mapping-1.htm#GUID-CFEFF2F3-85D3-46F6-A2F8-FDD55CD059F7)

If you'd like, you can sure your config with me (either `application.yml` or environment variables) and I'll review them.  Also, you can hit me up on the [Code Community Slack Channel](https://community.emccode.com).
